spring:
  zipkin:
    base-url: http://112.74.99.139:9411/
  application:
    name: user
  sleuth:
    sampler:
      probability: 1

server:
  port: 8800


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 10.8.12.31
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka/
